mutation userUpdateStats($stats:[UserStatsInput]){
        userUpdateStats(stats: $stats) {
          stats {
            _id,
            activity,
            timestamp
          }
        }
      }